### ISSUE TITLE
XML error -> You must supply a layout_width attribute

### ISSUE THREAD

**Issue by kenneth2008** [zawadz88/material-activity-chooser#3]
com.github.zawadz88.activitychooser.R.layout.activity_material_activity_chooser
May be in this layout don't have any width and height

**Comment by zawadz88** [comment]
Hi @kenneth2008,
Thanks for reporting this. 
This is due to the fact that styles are set via attributes and the Preview tool can't handle this. This can probably be solved by using `tools`.
I'll fix this :)

**Comment by kenneth2008** [comment]
Using TrackingActivityChooserActivity extends MaterialActivityChooserActivity.
It occur after I click the share button, the TrackingActivityChooserActivity has been called and the following message.....:
Process: com.XXX.XXXX.uat, PID: 2217
                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.XXX.XXXX.uat/com.XXX.XXXX.activity.TrackingActivityChooserActivity}: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: You must supply a layout_width attribute.

Caused by: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: You must supply a layout_width attribute.

**Comment by zawadz88** [comment]
Hi @kenneth2008,
On what device do you see this crash? Or is it on all devices?
Also, are you using the latest library version i.e. `0.2.2`?

**Comment by kenneth2008** [comment]
Q1: Android 6.0.1 on CAT S60 and Android 6.0.1 on Redmi Note 4X
Q2: Yes, 0.2.2,

At the beginning, I think it is because of this View:
<LinearLayout
        android:id="@+id/mac_bottom_sheet"

It didn't included any width and height attribute. then I gave them but also warning on line 10.
Finallaly,  I try to copy all of your code , attrs, style, and set that activity theme as MacTheme, success!

**Comment by zawadz88** [comment]
Ah OK, so you were missing `android:theme` for your custom Activity?
