### ISSUE TITLE
pass string to Tracker activity

### ISSUE THREAD

**Issue by feliperce** [zawadz88/material-activity-chooser#5]
Hello, it's not a issue, it's just an question.
I have a String that I need to pass to the Tracker activity, because I need it to track on firebase. but how to pass this string?

eg (what I tried), I need that bookId String to be called on onActivityClicked:

```
class TrackingBookShareActivity : MaterialActivityChooserActivity {

    private var firebaseAnalytics: FirebaseAnalytics? = null
    private var bookId: String = ""

    constructor(bookId: String) {
        this.bookId = bookId
    }

    constructor() {}

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        firebaseAnalytics = FirebaseAnalytics.getInstance(this)
    }

    override fun onActivityClicked(activity: ResolveInfo) {
        super.onActivityClicked(activity)
        firebaseEvent(firebaseAnalytics!!,
                FirebaseConst.CATEGORY_BOOK_DETAIL,
                "clicou em compartilhar", "$bookId / ${activity.activityInfo.packageName}")
    }
}
```

**Comment by zawadz88** [comment]
Hi @feliperce,
You shouldn't create a secondary constructor for an `Activity`. Android framework will always use the default constructor anyway.
In general, if you want to pass extra information to an Activity you need to pass them in a `Bundle` and read them in this `TrackingBookShareActivity`.
https://stackoverflow.com/questions/6707900/pass-a-string-from-one-activity-to-another-activity-in-android

So in your case if you're using sth like:
```
new MaterialActivityChooserBuilder(this)
                .withIntent(getDefaultShareIntent())
                .show();
```
I would add some custom field to that share Intent e.g.
```
shareTextIntent.putExtra("bookIdKey", "12345");
```
and in your `TrackingBookShareActivity` use:
```
getIntent().getStringExtra("bookIdKey")
```
to get that String.

**Comment by feliperce** [comment]
Thanks!
